/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misc.teknofest_scenario;

import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import jazari.factory.FactoryUtils;
import jazari.image_processing.ImageProcess;
import misc.teknofest_simulation.Simulation;

/**
 *
 * @author cezerilab
 */
public class ScenarioBuilder extends javax.swing.JFrame {

    String[] pathList = {
        "double click to select asset",
        "images/assets/car_agent.jpg",
        "images/assets/lamba_trafik.jpg",
        "images/assets/levha_dur.jpg",
        "images/assets/levha_durak.jpg",
        "images/assets/levha_engel.jpg",
        "images/assets/levha_girilmez.jpg",
        "images/assets/levha_hayvan.jpg",
        "images/assets/levha_ileri_veya_saga_yol.jpg",
        "images/assets/levha_ileri_veya_sola_yol.jpg",
        "images/assets/levha_park.jpg",
        "images/assets/levha_park_yapilmaz.jpg",
        "images/assets/levha_park_yapilmaz_2.jpg",
        "images/assets/levha_engelli.jpg",
        "images/assets/levha_saga_donulmez.jpg",
        "images/assets/levha_saga_mecburi_yol.jpg",
        "images/assets/levha_sola_donulmez.jpg",
        "images/assets/levha_sola_mecburi_yol.jpg",
        "images/assets/levha_tasit_trafigine_kapali.jpg",
        "images/assets/levha_yaya_gecidi.jpg",
        "images/assets/levha_yol_calismasi.jpg",
//        "images/assets/node_bitis.jpg",
        //        "images/assets/node_dort_yol.jpg",
//        "images/assets/node_pin_point.jpg",
        //        "images/assets/node_uc_yol.jpg",
        //        "images/assets/node_viraj.jpg",
//        "images/assets/yaya_cocuk.jpg",
        "images/assets/yaya_insan.jpg",
//        "images/assets/yaya_yasli.jpg",
        "images/assets/zemin_durak.jpg",
        "images/assets/zemin_engel.jpg",
        "images/assets/zemin_yaya_gecidi.jpg",
        "images/assets/.jpg",
//        "images/assets/.jpg",
//        "waypoint"
    };

    /**
     * Creates new form ScenarioBuilder
     */
    public ScenarioBuilder() {
        initComponents();
        lst_asset.setListData(formatPathList(pathList));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        txt_script.setFocusable(true);
        txt_script.requestFocus();

        BufferedImage img_parkur = ImageProcess.rgb2gray(ImageProcess.imread("images/assets/parkur.jpg"));
        getCanvas().setImage(img_parkur);

        lst_asset.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                JList list = (JList) evt.getSource();
                if (evt.getClickCount() == 2) {
                    if (lst_asset.getSelectedIndex() == 0) {
                        return;
                    } else if (lst_asset.getSelectedIndex() == pathList.length - 1) {
                        getCanvas().state = 2; //draw waypoints
                    } else {
                        getCanvas().state = 1;
                        getCanvas().tempAsset = ImageProcess.imread(pathList[lst_asset.getSelectedIndex()]);
                    }
                } else if (evt.getClickCount() == 3) {
                    // Triple-click detected
                    int index = list.locationToIndex(evt.getPoint());
                    System.out.println("triple click");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        panel_mini = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_asset = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_script = new javax.swing.JTextArea();
        btn_load = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_runSim = new javax.swing.JButton();
        txt_description = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        canvas = new PanelScenario(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jazari Robotaksi Scenario Builder");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panel_mini.setBackground(new java.awt.Color(204, 255, 204));
        panel_mini.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_mini.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panel_miniKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panel_miniLayout = new javax.swing.GroupLayout(panel_mini);
        panel_mini.setLayout(panel_miniLayout);
        panel_miniLayout.setHorizontalGroup(
            panel_miniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_miniLayout.setVerticalGroup(
            panel_miniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );

        lst_asset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lst_asset.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Select and Double-Click...", "Durak Alanı", "Durak Levhası", "Tekli Trafik Işığı", "Çiftli Trafik Işığı", "Dur Levhası", "Girilmez Levhası", "Taşıt Trafiğine Kapalı Levhası", "Yaya Geçidi Alanı", "Yaya Geçidi Levhası", "Park Levhası", "Park Yapılmaz Levhası", "Sola Mecburi Yol Levhası", "Sağa Mecburi Yol Levhası", "Sağa Dönülmez Levhası", "Sola Dönülmez Levhası", "İleri veya Sağa Mecburi Yol Levhası", "İleri veya Sola Mecburi Yol Levhası", "Engel Çizgisi Alanı", "Engel Levhası", "Yaya İnsan" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lst_asset.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_assetValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lst_asset);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_mini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_mini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_script.setEditable(false);
        txt_script.setColumns(20);
        txt_script.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txt_script.setRows(5);
        jScrollPane1.setViewportView(txt_script);

        btn_load.setBackground(new java.awt.Color(204, 204, 255));
        btn_load.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_load.setText("Open Script File");
        btn_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadActionPerformed(evt);
            }
        });

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_save.setText("Save Script File As");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Summary");

        btn_runSim.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_runSim.setText("RUN SIMULATION");
        btn_runSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_runSimActionPerformed(evt);
            }
        });

        txt_description.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_description.setText("Type your summary here ... ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(btn_load, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(btn_runSim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_description))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_load, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_runSim, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_description, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        canvas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        canvas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                canvasKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(canvas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lst_assetValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lst_assetValueChanged
        selectAsset();
    }//GEN-LAST:event_lst_assetValueChanged

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    }//GEN-LAST:event_formKeyPressed

    private void canvasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_canvasKeyPressed
    }//GEN-LAST:event_canvasKeyPressed

    private void panel_miniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panel_miniKeyPressed
    }//GEN-LAST:event_panel_miniKeyPressed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        saveScriptFile();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadActionPerformed
        loadScriptFile();
    }//GEN-LAST:event_btn_loadActionPerformed

    private void btn_runSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_runSimActionPerformed
        runSimulation();
    }//GEN-LAST:event_btn_runSimActionPerformed

    public PanelScenario getCanvas() {
        return (PanelScenario) canvas;
    }

    private void selectAsset() {
        String path = "";
        if (lst_asset.getSelectedIndex() == 0) {
            panel_mini.removeAll();
            repaint();
            return;
        } else if (lst_asset.getSelectedValue().equals("waypoint")) {
            return;
        } else {
            path = pathList[lst_asset.getSelectedIndex()];
        }
        panel_mini.removeAll();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT));
        ImageLabel label = new ImageLabel(imageIcon);
        //label.setLocation(29, 37);
        panel_mini.add(label);
        repaint();
    }

    private String[] formatPathList(String[] pathList) {
        String[] ret = new String[pathList.length];
        ret[0] = pathList[0];
        for (int i = 1; i < ret.length; i++) {
            String x = pathList[i].split("/")[2];
            x = x.split("\\.")[0];
            ret[i] = x;
        }
//        ret[ret.length - 1] = "waypoint";
        return ret;
    }

    private void saveScriptFile() {
        String str = "summary=" + txt_description.getText() + "\n" + txt_script.getText();
        FactoryUtils.writeToFile(str);
    }

    private void loadScriptFile() {
        String str = FactoryUtils.readFile();
        if (str == null) {
            return;
        }
        getCanvas().getAssetList().clear();
        String[] s = str.split("\n");
        txt_description.setText(s[0].split("=")[1]);
        String ek="";
        for (int i = 1; i < s.length; i++) {
            ek+=s[i] + "\n";
            String[] ss = s[i].split("=")[1].split(",");
            String imgPath = "images/assets/" + ss[0].split(":")[1] + ".jpg";
            BufferedImage img = ImageProcess.imread(imgPath);
            String name = ss[0].split(":")[1];
            String uuid=ss[1].split(":")[1];
            int rot = Integer.parseInt(ss[2].split(":")[1]);
            int mx = Integer.parseInt(ss[3].split(":")[1]);
            int my = Integer.parseInt(ss[4].split(":")[1]);
            float vx = Float.parseFloat(ss[5].split(":")[1]);
            float vy = Float.parseFloat(ss[6].split(":")[1]);
            AssetComponent ac = new AssetComponent(getCanvas(),uuid, img, name, rot, mx, my, vx, vy);
            ac.setRotationDegree(rot,false);
            if (ss.length > 7) {
                String[] q = ss[7].split(";");
                int n = q.length;
                for (int j = 0; j < n; j++) {
                    AssetComponent temp = new AssetComponent(getCanvas(),q[j], img, "", 0, mx, my, vx, vy);
                    ac.listNeighborNodes.add(temp);
                }
            }
            getCanvas().getAssetList().add(ac);
        }
        txt_script.setText(ek);
        getCanvas().repaint();
    }

    private void runSimulation() {
        new Simulation().runApplet();
    }

    class ImageLabel extends JLabel {

        public ImageLabel(String img) {
            this(new ImageIcon(img));
        }

        public ImageLabel(ImageIcon icon) {
            setIcon(icon);
            setIconTextGap(0);
            setBorder(null);
            setText(null);
            setSize(icon.getImage().getWidth(null), icon.getImage().getHeight(null));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScenarioBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScenarioBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScenarioBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScenarioBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScenarioBuilder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_load;
    private javax.swing.JButton btn_runSim;
    private javax.swing.JButton btn_save;
    public javax.swing.JPanel canvas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JList<String> lst_asset;
    private javax.swing.JPanel panel_mini;
    private javax.swing.JTextField txt_description;
    public javax.swing.JTextArea txt_script;
    // End of variables declaration//GEN-END:variables
}
